// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV6VCHZgiuJXa-S2WTX04uwwGLRzgmN34',
    appId: '1:453488761295:web:9766cb1dc0e6adb099daba',
    messagingSenderId: '453488761295',
    projectId: 'spazigo-95665',
    authDomain: 'spazigo-95665.firebaseapp.com',
    storageBucket: 'spazigo-95665.firebasestorage.app',
    measurementId: 'G-469Z5BVEG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8SzCs4iE-WkaLLZnozufLuUN1_am3UY',
    appId: '1:453488761295:android:d6c7a9c472de083f99daba',
    messagingSenderId: '453488761295',
    projectId: 'spazigo-95665',
    storageBucket: 'spazigo-95665.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV6VCHZgiuJXa-S2WTX04uwwGLRzgmN34',
    appId: '1:453488761295:web:24c44d6e5e99e01099daba',
    messagingSenderId: '453488761295',
    projectId: 'spazigo-95665',
    authDomain: 'spazigo-95665.firebaseapp.com',
    storageBucket: 'spazigo-95665.firebasestorage.app',
    measurementId: 'G-SH78HRZ80S',
  );
}
